---

# disable loadbalancer then webserver(s), reset database server
# then start things back up backend=>frontend

- hosts: loadbalancer
  become: true
  tasks:
      service: name=nginx state=stopped

- hosts: webserver
  become: true
  tasks:
      service: name=apache2 state=stopped

- hosts: database
  become: true
  tasks:
      service: name=nginx state=restarted

- hosts: webserver
  become: true
  tasks:
      service: name=apache2 state=started

- hosts: loadbalancer
  become: true
  tasks:
      service: name=nginx state=started

