---
- name: install tools
  apt: name={{item}} state=present update_cache=yes cache_valid_time=86400
  with_items:
     - python-mysqldb

- name: install mysql-server
  apt: name=mysql-server state=present update_cache=yes cache_valid_time=86400

- name: ensure mysql listening on all ports
  lineinfile: dest=/etc/mysql/my.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
  notify: restart mysql

- name: ensure mysql started
  service: name=mysql state=started enabled=yes

- name: config demo database
  mysql_db: name=demo state=present

- name: create demo user
  mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

